### ISSUE TITLE
emoji

### ISSUE THREAD

**Issue by arnaudjuracek** [brocessing/bro-logo#1]
![18685042](https://cloud.githubusercontent.com/assets/2837959/18829941/dce23f02-83de-11e6-842a-9115b276430d.png)
http://emojipedia.org/flexed-biceps/

**Comment by leoternoir** [comment]
I kind of like the aspect of it but to me, we can't use a common emoji as logo.

Also, what about copyrights ? I think our logo needs to be MIT licensed.
